name: Build Android APK
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Web Assets (Vite)
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Inject google-services.json
        env:
          FIREBASE_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo "$FIREBASE_JSON" > ./android/app/google-services.json

      - name: Build Android APK
        working-directory: ./android
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MessApp-Debug-APK
          path: android/app/build/outputs/apk/debug/app-debug.apk
